version: '3'

services:

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 1234:5432

  python:
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8000:8000
    stdin_open: true


volumes:
  postgres-data: